FROM rasa/rasa-sdk:3.6.2

WORKDIR /app

USER root

COPY ./actions /app/actions
COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

USER 1001

EXPOSE 5055

CMD ["start", "--actions", "actions", "--port", "5055"]